language: java
sudo: false
dist: trusty
jdk: oraclejdk8
install: true
script:
- npm install -g polymer-cli
- npm install -g bower
- "./gradlew -version"
- "./gradlew build --info --stacktrace"
- "./gradlew archiveZip"
notifications:
  email: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: D6mn8SMxs37bsb2uNTYDW1WeZ4PEvHuwQ2PfECXfhpG36A7W8p5li6zIo4hVhTW3JEw0j0fjYCYTZbVDRe8K+3cB9iZ/qBBGsp33r4FskB50Pe8LpybtKeOauJ2GVkjvmcoRq+A/Ti4Z7Q94NhNuQ1wIbf55iga9f/iRcXA5Pm20gEyXFL2yOYcvTOx55l5xUk5rb38ew5RqyJiHf36ZZjzeJDutUzHUC5cqfoU+ZIorpLrQqshHN0clCJH7zfNtiL8Xa0Gig0IRY+DoSzbE9V7jRHM8x9AZHY9QxvMPtaPaxpBPQShWn/E5F9wFxPK3vxy48GkbOA6id/coK5OrJftE9KO34JyZGDF5Uq11PThMEnr/0whflGZHUkNJiqJceQ6UvgkFPKCLEXkTDoTBT18xRziP/12HnZRAMU4dAiqlXs0OYv3SxA/UkCtjFfgPSk+morTSRgq0OJcK53VM9jC8NnGBZkWStLhu4eeYwyg6sJWApCEmI6UK35tuorK0TSq/q68JPHSsAz2SkqQlM3ds2DjvmhT6oOUaRQul94lv8DfkYPW1c/0jImnknK2pKhPAe5f8afvV9j1Hrgi8xotpw0rQLz0eN+Z9dpNJP4nzWa9AIjEHlGeTPUGrC4723qzdNf7zzo7hKXuROZkHu7eRFWCV3Fk7zdDc7F515Gc=
  file_glob: true
  file:
    - build/distributions/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  global:
  - GRADLE_OPTS="-Xms256m"
  - JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
    --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/sun.net.dns=ALL-UNNAMED
    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED
    --add-opens=java.base/sun.nio.ch=ALL-UNNAMED'
